import type { Pet, Application, User, VaccinationRecord } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'demo',
    email: 'demo@example.com',
    firstName: 'Demo',
    lastName: 'User',
    phone: '+1234567890',
    address: '123 Demo Street',
    bio: 'Pet lover and animal enthusiast',
  },
  {
    id: '2',
    username: 'john_doe',
    email: 'john@example.com',
    firstName: 'John',
    lastName: 'Doe',
    phone: '+1987654321',
    address: '456 Pet Avenue',
    bio: 'Experienced pet owner',
  },
];

export const mockVaccinations: VaccinationRecord[] = [
  {
    id: '1',
    vaccineName: 'Rabies',
    date: new Date('2024-01-15'),
    nextDueDate: new Date('2025-01-15'),
    veterinarian: 'Dr. Smith',
    notes: 'Annual vaccination',
  },
  {
    id: '2',
    vaccineName: 'DHPP',
    date: new Date('2024-02-01'),
    nextDueDate: new Date('2025-02-01'),
    veterinarian: 'Dr. Johnson',
    notes: 'Core vaccines',
  },
];

export const mockPets: Pet[] = [
  {
    id: '1',
    ownerId: '1',
    name: 'Buddy',
    age: 3,
    sex: 'male',
    species: 'Dog',
    breed: 'Golden Retriever',
    images: ['https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=300&fit=crop'],
    vaccination: mockVaccinations,
    description: 'A friendly and energetic Golden Retriever who loves playing fetch and going for walks.',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    ownerId: '1',
    name: 'Whiskers',
    age: 2,
    sex: 'female',
    species: 'Cat',
    breed: 'Persian',
    images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=300&fit=crop'],
    vaccination: [mockVaccinations[0]],
    description: 'A gentle and calm Persian cat who enjoys quiet evenings and gentle pets.',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    ownerId: '2',
    name: 'Max',
    age: 5,
    sex: 'male',
    species: 'Dog',
    breed: 'Labrador',
    images: ['https://images.unsplash.com/photo-1543466835-00a4907b8b52?w=400&h=300&fit=crop'],
    vaccination: mockVaccinations,
    description: 'A loyal and intelligent Labrador who is great with kids and other pets.',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
];

export const mockApplications: Application[] = [
  {
    id: '1',
    petId: '1',
    ownerId: '1',
    title: 'Looking for a loving home for Buddy',
    description: 'Due to my relocation for work, I can no longer care for Buddy. He is a wonderful dog who deserves a loving family. He is house-trained, good with kids, and loves outdoor activities.',
    status: 'open',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
    pet: mockPets[0],
    owner: mockUsers[0],
  },
  {
    id: '2',
    petId: '2',
    ownerId: '1',
    title: 'Whiskers needs a quiet home',
    description: 'Whiskers is a gentle cat who would do well in a calm household. She is spayed, vaccinated, and very affectionate. Perfect for someone looking for a companion.',
    status: 'open',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
    pet: mockPets[1],
    owner: mockUsers[0],
  },
  {
    id: '3',
    petId: '3',
    ownerId: '2',
    title: 'Max needs a new family',
    description: 'Max is a wonderful dog but I can no longer provide the exercise and attention he needs. He would be perfect for an active family with a yard.',
    status: 'pending',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
    pet: mockPets[2],
    owner: mockUsers[1],
  },
];
