spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: jdbc:sqlserver://${LOCAL_DB_URL};databaseName=${LOCAL_DB_NAME};encrypt=true;trustServerCertificate=true
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
      use_nationalized_character_data: true
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

jwt:
  secret-key: ${TOKEN_SECRET_KEY}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000
